### ISSUE TITLE
VR-Touch: Left Eye only @ Oculus

### ISSUE THREAD

**Issue by imminaa** [xLAva/JediOutcastLinux#81]
Hey,

using the precompiled windows binaries for VR-Touch the right eye doesn't work in the Oculus Rift.

All you get is a flickering Left Eye.

EDIT: Building using OVR causes a black screen and using OpenVR simply flickers

**Comment by xLAva** [comment]
Hi.

Can you give us more information?

What Windows version are you using?
Which hardware version of the Oculus Rift are you using?
Do you use the newest Oculus software/driver?
Which graphics card are you using?

**Comment by imminaa** [comment]
Hey,
I'm on the Windows 10 Fall Creators Update using a Oculus Rift CV1 with the latest Oculus updates(I've also tested it with the beta update).
The GPU is a GTX 1080.

The release builds from August that can be downloaded work fine(left eye only). It's just the VR-Touch branch that doesnt seem to cooperate with my Oculus.

**Comment by serkuan** [comment]
The release builds that can be downloaded work fine. It's just the VR-Touch branch that doesnt seem to cooperate with my Oculus.

**Comment by lee3701** [comment]
I am also having this issue as soon as I added the touch controller support. I replaced the 3 files as instructed and loaded jk2sp. 

Wind 10 home Version 10.0.17134 Build 17134
Oculus Rift Firmware version 709/b1ae4f61ae
Yes installed latest oculus software
GTX 1060

**Comment by An-reo** [comment]
Hi there,

First off I’d like to say you guys made an amazing job, it is a dream come true to play this game in VR.

I am also experiencing the same bug plus I had to turn off the boundaries in steam because I was getting some weird spiral effect in the lower half of the screen.

It is exactly like described above, the right display is black and the left one is flickering. The old .exe file without touch support works just fine.

It is a damn shame, because otherwise it works great! :)

Are you looking into this? Would even throw in some coin on Patreon to play this.

Specs:
Windows 10 - newest update
Intel i7-7700
GTX 1070
Oculus CV1 - newest update

Thanks!

**Comment by RavMahov** [comment]
Hello there,

Almost the same thing happens on OpenVR with HTC Vive (left eye only) + the screen is flickering to black the whole time.
Windows 7
Intel i5 4670K
GTX 10xx with newest drivers.

Maybe it was even fixed at some point, but I'm using the newest binaries from one of @shinyquagsire23 branches, which still seem outdated.

Thanks for all the work so far @xLAva, @shinyquagsire23 and the others

**Comment by TyXe0** [comment]
Hello,
I have the same problem.
I think since the update of steamVR.

**Comment by TyXe0** [comment]
Ok, problem resolved for me I downgrade steamVR to the version 1.2.10

**Comment by benhollio** [comment]
> 
> 
> Ok, problem resolved for me I downgrade steamVR to the version 1.2.10

How did you downgrade SteamVR? I am having no luck at all.

**Comment by xLAva** [comment]
This should be fixed by #89
If it still happens - please re-open the issue.
